# Generated by Django 6.0.5 on 2026-07-01 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Senha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_paciente', models.CharField(max_length=100)),
                ('numero', models.PositiveBigIntegerField()),
                ('tipo_servico', models.CharField(choices=[('consulta', 'Consulta'), ('exame', 'Exame'), ('retorno', 'Retorno')], max_length=20)),
                ('prioridade', models.CharField(choices=[('minima', 'Minima'), ('baixa', 'Baixa'), ('media', 'Media'), ('alta', 'Alta'), ('maxima', 'Maxima')], default='media', max_length=20)),
                ('status', models.CharField(choices=[('aguardando_recepcao', 'Aguardando Recepção'), ('aguardando_consultorio', 'Aguardando Consultório'), ('chamado', 'Chamado'), ('atendido', 'Atendido'), ('cancelado', 'Cancelado')], default='aguardando_recepcao', max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('chamado_recepcao', models.DateTimeField(blank=True, null=True)),
                ('chamado_consultorio', models.DateTimeField(blank=True, null=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('consultorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='atendimento_app.consultorio')),
            ],
            options={
                'ordering': ['-prioridade', 'criado_em'],
            },
        ),
    ]
