# Generated by Django 6.0.5 on 2026-07-15 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento_app', '0002_alter_consultorio_options_alter_senha_numero_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='senha',
            options={'ordering': ['-prioridade', 'criado_em'], 'verbose_name': 'Senha', 'verbose_name_plural': 'Senhas'},
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
    ]
